-- 코드를 입력하세요
SELECT R.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(avg(REVIEW_SCORE), 2) AS SCORE
from REST_INFO AS I JOIN REST_REVIEW AS R
on I.REST_ID = R.REST_ID
where ADDRESS like '서울%'
group by REST_NAME
order by SCORE DESC, FAVORITES DESC