SELECT CD.ID AS ID, CD.GENOTYPE AS GENOTYPE, PD.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS CD 
LEFT JOIN ECOLI_DATA AS PD
ON CD.PARENT_ID = PD.ID
WHERE CD.PARENT_ID IS NOT NULL
AND CD.GENOTYPE & PD.GENOTYPE = PD.GENOTYPE
ORDER BY CD.ID ASC